import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', 'Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'surface-tint':              '#4edea3',
                'on-primary-fixed-variant':  '#005236',
                'on-error-container':        '#ffdad6',
                'inverse-primary':           '#006c49',
                'secondary-fixed':           '#e1e0ff',
                'primary-fixed':             '#6ffbbe',
                'primary':                   '#4edea3',
                'on-tertiary-container':     '#523200',
                'surface-container-highest': '#2d3449',
                'primary-container':         '#10b981',
                'primary-fixed-dim':         '#4edea3',
                'surface':                   '#0b1326',
                'on-secondary-container':    '#b0b2ff',
                'tertiary-container':        '#e29100',
                'surface-dim':               '#0b1326',
                'secondary':                 '#c0c1ff',
                'on-error':                  '#690005',
                'error':                     '#ffb4ab',
                'on-secondary':              '#1000a9',
                'surface-container-high':    '#222a3d',
                'on-primary-container':      '#00422b',
                'inverse-on-surface':        '#283044',
                'on-tertiary':               '#472a00',
                'on-background':             '#dae2fd',
                'inverse-surface':           '#dae2fd',
                'surface-container-lowest':  '#060e20',
                'on-surface':                '#dae2fd',
                'outline-variant':           '#3c4a42',
                'on-surface-variant':        '#bbcabf',
                'tertiary-fixed':            '#ffddb8',
                'secondary-container':       '#3131c0',
                'error-container':           '#93000a',
                'surface-variant':           '#2d3449',
                'surface-container-low':     '#131b2e',
                'surface-container':         '#171f33',
                'surface-bright':            '#31394d',
                'on-primary-fixed':          '#002113',
                'on-tertiary-fixed-variant': '#653e00',
                'on-secondary-fixed-variant':'#2f2ebe',
                'outline':                   '#86948a',
                'tertiary':                  '#ffb95f',
                'secondary-fixed-dim':       '#c0c1ff',
                'on-primary':                '#003824',
                'background':                '#0b1326',
                'on-tertiary-fixed':         '#2a1700',
                'tertiary-fixed-dim':        '#ffb95f',
                'on-secondary-fixed':        '#07006c',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg:      '0.5rem',
                xl:      '0.75rem',
                '2xl':   '1rem',
                '3xl':   '1.5rem',
                full:    '9999px',
            },
            spacing: {
                'margin-mobile':   '16px',
                'stack-sm':        '12px',
                'container-max':   '1280px',
                gutter:            '24px',
                'margin-desktop':  '40px',
                'stack-lg':        '48px',
                'stack-md':        '24px',
                base:              '8px',
            },
            maxWidth: {
                'container-max': '1280px',
            },
        },
    },

    plugins: [forms],
};
